---

- name: Install linux headers
  apt:
    name="{{ pkgs }}"
    state="present"
    update_cache=True
    install_recommends=False
  vars:
    pkgs:
    - linux-headers-amd64

- name: Accept license
  ansible.builtin.debconf:
    name: zfs-dkms
    question: zfs-dkms/note-incompatible-licenses
    value: true
    vtype: boolean

- name: Install zfs-dkms
  apt:
    name="{{ pkgs }}"
    state="present"
    update_cache=False
    install_recommends=False
  vars:
    pkgs:
    - zfs-dkms
  when: ansible_lsb.major_release|int >= 11

- name: Load zfs module
  modprobe:
    name: zfs
    state: present

- name: Install zfsutils-linux
  apt:
    name="{{ pkgs }}"
    state="present"
    update_cache=False
    install_recommends=False
  vars:
    pkgs:
    - zfsutils-linux
  when: ansible_lsb.major_release|int >= 11

- name: Install zfsnap packages
  apt:
    name="{{ pkgs }}"
    state="present"
    update_cache=False
    install_recommends=False
  vars:
    pkgs:
    - zfsnap
