---

- name: Create users
  user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    state: present
    shell: /bin/bash
    system: no
    createhome: yes
    home: "/home/{{ item.name }}"
  with_items: "{{ users }}"

