galaxy_info:
  role_name: ansible_groups
  author: Pascal Geiser
  description: Setup groups for user accounts
  license: license MIT
  min_ansible_version: 2.8
  platforms:
  - name: Debian
    versions:
      - buster
  galaxy_tags:
    - debian
    - buster
    - group
dependencies: []

