galaxy_info:
  role_name: ansible_docker
  author: Pascal Geiser
  description: Install docker.
  license: license MIT
  min_ansible_version: 2.8
  platforms:
  - name: Debian
    versions:
      - buster
  galaxy_tags:
    - debian
    - docker
dependencies: []

